# Setup
title:               Raja Williams
tagline:             '@rajaw.org'
description:         'Personal website of Raja Williams'
url:                 https://rajaw.org
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Raja Williams
  url:               https://rajaw.org

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.0.0
